### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by blauc** [bioexcel/gromacs_bpg#1]
- Generating your own forcefield file: lots of focus on own force-field, but you can also generate your own topology for a given system, where you circumvent the "making your own force-field" alltogether and is the approach used for ligand relative binding free energy simulations - use the standard forcefiled and pdb2gmx procedure, then use a parameter-generating tool like `antechamber` with `acpype` for amber or `cgenff` for CHARMM, then add the generated topolgy files to your topology via include statement
 - Generating a system from a GROMACS structure file: to start with `insert-molecule` is good for the scenario that you describe, but not so common for protein simulations, maybe change header: generating a system of replicates from a structure file
 - Creating a charge-neutral system: Adding ions is also good to come close to physiological salt concentrations; so you would want to add ions even when the charge was not 0
 - `genion` keeps the ions a certain distance from your protein, which might be worth mentioning
 - Example parameter file: the order does not matter (instead of should); same command twice should give a warning if I'm right, and does not override
 - The `tau-t` section: mention that the deviation is the same for all `tau-t`, for `v-rescale` there is no `tau-t` that is incorrect physically
 - generating an index file: good to mention that `gmx select` can generate index files as well for more complex scenarios

**Comment by jsindt** [comment]
Thanks for the comments -- I've addressed them in the new version.
